# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlergiasMedicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergia', models.CharField(blank=True, max_length=1000)),
                ('reaccion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlergiasMedicamentosLatex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaccion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlergiasMedicamentosTela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaccion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPersonalesCancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=1000)),
                ('tratamiento', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPersonalesOtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro_antecedentes_personales', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesQuirurgicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_cirugia', models.CharField(blank=True, max_length=1000)),
                ('year', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complementos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(blank=True, max_length=1000)),
                ('dosis', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrogadiccionOtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otra', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('rfc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=1000)),
                ('ap_paterno', models.CharField(max_length=1000)),
                ('ap_materno', models.CharField(max_length=1000)),
                ('edad_paciente', models.CharField(blank=True, max_length=1000)),
                ('fecha_de_nacimiento', models.CharField(max_length=100)),
                ('sexo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=18)),
                ('estado_civil', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Uni\xf3n Libre', 'Uni\xf3n Libre')], max_length=55)),
                ('num_hijos', models.CharField(blank=True, max_length=1000)),
                ('medico_que_refiere', models.CharField(blank=True, max_length=1000)),
                ('motivo_de_consulta', models.CharField(blank=True, max_length=1000)),
                ('usuario', models.CharField(blank=True, max_length=1000)),
                ('antecedentes_personales', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ninguna', 'Ninguna'), ('Enf. del coraz\xf3n', 'Enf. del coraz\xf3n'), ('Presi\xf3n Alta', 'Presi\xf3n Alta'), ('Infarto/Embolia', 'Infarto/Embolia'), ('Apnea del Sue\xf1o', 'Apnea del Sue\xf1o'), ('Enf. Coronaria', 'Enf. Coronaria'), ('Depresi\xf3n', 'Depresi\xf3n'), ('Ansiedad', 'Ansiedad'), ('Sangrados', 'Sangrados'), ('Hepatitis A B o C', 'Hepatitis A B o C'), ('HIV', 'HIV'), ('Diabetes-Dieta', 'Diabetes-Dieta'), ('Diabetes-Meds', 'Diabetes-Meds'), ('Diabetes-Insulina', 'Diabetes-Insulina'), ('Colesterol Alto', 'Colesterol Alto'), ('Convulsiones', 'Convulsiones'), ('Desmayos', 'Desmayos'), ('Artritis', 'Artritis'), ('Asma', 'Asma'), ('Enfisema', 'Enfisema'), ('Osteoporosis', 'Osteoporosis'), ('Alergia:Comida', 'Alergia:Comida'), ('Alergia:Estacional', 'Alergia:Estacional'), ('Tuberculosis', 'Tuberculosis'), ('Hipotiroidismo', 'Hipotiroidismo'), ('Hipertiroidismo', 'Hipertiroidismo'), ('C\xe1ncer', 'C\xe1ncer'), ('Otra', 'Otra')], max_length=346)),
                ('alergias_medicamentos', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ninguna alergia conocida a Medicamentos', 'Ninguna alergia conocida a Medicamentos'), ('L\xe1tex', 'L\xe1tex'), ('Tela adhesiva', 'Tela adhesiva'), ('Otra', 'Otra')], max_length=64)),
                ('tabaquismo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nunca', 'Nunca'), ('Abandon\xf3?', 'Abandon\xf3?'), ('# d\xeda?', '# d\xeda?'), ('Pipa', 'Pipa'), ('Puros', 'Puros')], max_length=33)),
                ('dias_tabaquismo', models.CharField(blank=True, max_length=1000)),
                ('year_tabaquismo', models.CharField(blank=True, max_length=1000)),
                ('alcoholismo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nunca', 'Nunca'), ('Social', 'Social'), ('Diario', 'Diario'), ('Embriaguez', 'Embriaguez')], max_length=30)),
                ('year_alcoholismo', models.CharField(blank=True, max_length=1000)),
                ('drogadiccion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nunca', 'Nunca'), ('Mariguana', 'Mariguana'), ('Anfetaminas', 'Anfetaminas'), ('Otras', 'Otras')], max_length=33)),
                ('year_drogadiccion', models.CharField(blank=True, max_length=1000)),
                ('ejercicio', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nunca', 'Nunca'), ('1-2x/semana', '1-2x/semana'), ('3-4x/semana', '3-4x/semana'), ('5-7x/semana', '5-7x/semana')], max_length=41)),
                ('year_ejercicio', models.CharField(blank=True, max_length=1000)),
                ('cafeina', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nunca', 'Nunca'), ('Ocasional', 'Ocasional'), ('Diario', 'Diario')], max_length=22)),
                ('year_cafeina', models.CharField(blank=True, max_length=1000)),
                ('creencia_religiosa', models.CharField(blank=True, max_length=1000)),
                ('nivel_escolaridad', models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Licenciatura', 'Licenciatura'), ('Post Grado', 'Post Grado')], max_length=100)),
                ('tiempo_escolaridad', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Trunca', 'Trunca'), ('Completa', 'Completa')], max_length=15)),
                ('alcance_escolaridad', models.CharField(blank=True, max_length=1000)),
                ('edad_padre', models.CharField(blank=True, max_length=1000)),
                ('antecedentes_padre', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vivo', 'Vivo'), ('Finado', 'Finado'), ('Alta Presi\xf3n Arterial', 'Alta Presi\xf3n Arterial'), ('Diabetes', 'Diabetes'), ('Colesterol', 'Colesterol'), ('C\xe1ncer', 'C\xe1ncer'), ('Otro', 'Otro')], max_length=65)),
                ('causa_muerte_padre', models.CharField(blank=True, max_length=300)),
                ('edad_madre', models.CharField(blank=True, max_length=1000)),
                ('antecedentes_madre', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Vivo', 'Vivo'), ('Finado', 'Finado'), ('Alta Presi\xf3n Arterial', 'Alta Presi\xf3n Arterial'), ('Diabetes', 'Diabetes'), ('Colesterol', 'Colesterol'), ('C\xe1ncer', 'C\xe1ncer'), ('Otro', 'Otro')], max_length=65)),
                ('causa_muerte_madre', models.CharField(blank=True, max_length=1000)),
                ('edad_hermanos', models.CharField(blank=True, max_length=1000)),
                ('num_hermanos_vivos', models.CharField(blank=True, max_length=1000)),
                ('num_hermanos_finados', models.CharField(blank=True, max_length=1000)),
                ('antecedentes_hermanos', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Alta Presi\xf3n Arterial', 'Alta Presi\xf3n Arterial'), ('Diabetes', 'Diabetes'), ('Colesterol', 'Colesterol'), ('C\xe1ncer', 'C\xe1ncer'), ('Otro', 'Otro')], max_length=53)),
                ('practica_deporte', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=5)),
                ('que_deporte', models.CharField(blank=True, max_length=1000)),
                ('lado_dominante', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Diestro', 'Diestro'), ('Zurdo', 'Zurdo')], max_length=13)),
                ('nivel', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Amateur', 'Amateur'), ('Profesional', 'Profesional')], max_length=19)),
                ('esta_embarazada', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=5)),
                ('esta_amamantando', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=5)),
                ('num_embarazos', models.CharField(blank=True, max_length=1000)),
                ('tipos_de_anticonceptivos', models.CharField(blank=True, max_length=1000)),
                ('fecha_de_ultima_regla', models.CharField(blank=True, max_length=1000)),
                ('fecha_gripe', models.CharField(blank=True, max_length=1000)),
                ('fecha_tetanos', models.CharField(blank=True, max_length=1000)),
                ('otra_inmunizacion', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Otra', 'Otra'), ('Ninguna', 'Ninguna')], max_length=12)),
                ('padecimiento_actual', models.TextField(blank=True, max_length=100000)),
                ('idx', models.CharField(blank=True, max_length=1000)),
                ('aseguranza', models.CharField(blank=True, choices=[('Banorte', 'Banorte'), ('Axxa', 'Axxa'), ('Allianz', 'Allianz'), ('GNP', 'GNP'), ('La Latino Seguros', 'La Latino Seguros'), ('MAPFRE', 'MAPFRE'), ('Metlife', 'Metlife'), ('Seguros Atlas', 'Seguros Atlas'), ('Seguros Monterrey', 'Seguros Monterrey')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HermanosCancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='HermanosCausaMuerte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causamuerte', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='HermanosOtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='HojaEvolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(blank=True, max_length=1000)),
                ('evolucion', models.TextField(blank=True, max_length=100000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='HojaTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(blank=True, max_length=1000)),
                ('tx', models.TextField(blank=True, max_length=100000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='InmunizacionesOtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otra', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='MadreCancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='MadreOtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentosPrescritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(blank=True, max_length=1000)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='PadreCancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='PadreOtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(blank=True, max_length=1000)),
                ('fk_expedientemedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_usuario', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TipoUsuario')),
            ],
        ),
        migrations.AddField(
            model_name='drogadiccionotras',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
        migrations.AddField(
            model_name='complementos',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
        migrations.AddField(
            model_name='antecedentesquirurgicos',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
        migrations.AddField(
            model_name='antecedentespersonalesotros',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
        migrations.AddField(
            model_name='antecedentespersonalescancer',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
        migrations.AddField(
            model_name='alergiasmedicamentostela',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
        migrations.AddField(
            model_name='alergiasmedicamentoslatex',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
        migrations.AddField(
            model_name='alergiasmedicamentos',
            name='fk_expedientemedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ExpedienteMedico'),
        ),
    ]
