# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_expedientemedico_menarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientemedico',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to='archivos_physiomed'),
        ),
    ]
